### ISSUE TITLE
Update comparison table for django-components

### ISSUE THREAD

**Issue by JuroOravec** [wrabit/django-cotton#114]
Hi, I'm one of maintainers over at [django-components](https://github.com/EmilStenstrom/django-components). We had [a discussion on django-cotton](https://github.com/EmilStenstrom/django-components/discussions/552). There was a lot of great ideas in django-cotton that we added to django-components!

With that in mind, the comparison table is outdated. Below are features that are now supported. Would you update the README, or shall I create a PR?

Thanks!

---

- Q: `Create component in one step?`
	- A: ✅ (Technically yes with [single-file components](https://github.com/EmilStenstrom/django-components#using-single-file-components))
- Q: `Dynamic Components`
  - A: ✅ [See here](https://github.com/EmilStenstrom/django-components#dynamic-components)
- Q: `Dynamic Attributes`
  - A: ✅ (with `django-expr`) [See here](https://github.com/EmilStenstrom/django-components#evaluating-python-expressions-in-template)
- Q: `Declare Variables in Component View`
  - A: ✅ (Technically yes with `"as var"` syntax, e.g. `{% expr 'text-red-800' as theme_class %}`)
- Q: `Django Template Expressions in Attribute Values`
  - A: ✅ [See here](https://github.com/EmilStenstrom/django-components#use-template-tags-inside-component-inputs)
- Q: `Multi-line Component Tags`
  - A: ✅ [See here](https://github.com/EmilStenstrom/django-components#multi-line-tags)

**Comment by wrabit** [comment]
Thanks for the update - will take a look and update the table
