### ISSUE TITLE
Some whitespace between two variables inside a slot gets removed

### ISSUE THREAD

**Issue by KucharczykL** [wrabit/django-cotton#120]
# Steps to reproduce

1. Create a template with a slot
2. When including the template, put inside the slot two variables with space in between (tried non-breaking space and some other spaces, like em space)
3. There is no character between the two variable values in the output

# What do you expect

I expect any characters between variables to be preserved, including spaces.

# Additional info

Putting a linebreak in between the two variables ends up creating/preserving a space between them.

`cotton/vartest.html`
```django
{{ slot }}
```

`index.html`
```django
<!-- var1="one" var2="two" -->
<c-vartest>
{{var1}} {{var2}}
</c-vartest>
```

Output:
`onetwo`

**Comment by wrabit** [comment]
Fixed in [v0.9.37](https://github.com/wrabit/django-cotton/releases/tag/v0.9.37)
