### ISSUE TITLE
Conditionally applying html attributes

### ISSUE THREAD

**Issue by redmondscales** [wrabit/django-cotton#124]
Thanks for the work on this project, been great so far.

I have an issue/question on how to deal with conditional attributes when calling a component. This came up trying to override some templates from django-allauth.

For example this block is part of the allauth field template (account/allauth/elements/field.html)

```html
<input {% if attrs.required %}required{% endif %}
               {% if attrs.disabled %}disabled{% endif %}
               {% if attrs.readonly %}readonly{% endif %}
               {% if attrs.checked %}checked{% endif %}
               {% if attrs.name %}name="{{ attrs.name }}"{% endif %}
               {% if attrs.id %}id="{{ attrs.id }}"{% endif %}
               {% if attrs.placeholder %}placeholder="{{ attrs.placeholder }}"{% endif %}
               {% if attrs.autocomplete %}autocomplete="{{ attrs.autocomplete }}"{% endif %}
               {% if attrs.value is not None %}value="{{ attrs.value }}"{% endif %}
               type="{{ attrs.type }}">
```

They are conditionally applying attributes like "required" etc.

Now ideally I'd like to do this and replace the input with a custom c-input (just the required attribute for this example)

```html
<c-input type="text" {% if some_boolean %} required {% endif %} />
```
and have the component just like this
```html
# templates/cotton/input.html
<input  {{attrs}} />
```

Unfortunately this causes a TemplateSyntaxError
Invalid block tag on line 7: 'endif', expected 'end_cotton_component'. Did you forget to register or load this tag?

Looks like blocks as such {% if %} aren't allowed in the component call?

For now I can handle this by moving the conditionals down into the component itself like this

```html
# templates/cotton/input.html
<c-vars required/>
<input {% if required %}required{%endif%} {{attrs}} />
```
then use it like this

```html
<c-input type="text" required={{some_boolean}} />
```

Which works but it takes away from the benefit/flexibility of the attrs functionality you have.

So my question is, is it possible to conditionally apply attributes when calling a cotton component? This is mainly for HTML attributes that should be present or not like required, checked, disabled etc.

Hopefully I haven't missed anything obvious.

**Comment by wrabit** [comment]
@redmondscales Hello and thanks for the issue + trying out cotton!

For now, probably the best is:

```html
<c-input type="text" :required="{{ some_boolean }}" />
```

This will provide 'True' to the dynamic attribute which will evaluate as a python/DTL `True`. 

If you need more logic then you can deliver other string literals (None, True, False, other types) to the dynamic attribute using `{{` or `{%`. It can get quite verbose, but I have an open branch of work that will deal with such expressions in the future.

**Comment by redmondscales** [comment]
Thanks for the reply
