### ISSUE TITLE
Built-in template tags relying on RequestContext broken

### ISSUE THREAD

**Issue by fbinz** [wrabit/django-cotton#126]
### Praise

First off, I want to thank you for this awesome library!
I wrote something superficially [similar](https://github.com/fbinz/django-components-preprocessor), but it's just as a wrapper for django-components. 
Your solution really takes away all the boilerplate and makes component based design really fun in Django. :tada: 

### Problem

I noticed a minor issue, when using the new [querystring](https://docs.djangoproject.com/en/5.1/ref/templates/builtins/#querystring) template tag, which usees `request.context` internally.
This breaks, when used inside a `django-cotton` component, because of flattening the context into a plain dict during rendering: [Link](https://github.com/wrabit/django-cotton/blob/main/django_cotton/templatetags/_component.py#L52)

I'm not sure, what a good fix would be. Maybe re-creating a `RequestContext` object after flattening? Or maybe not flattening at all? I'm not entirely sure why it is needed.

In my particular case, this is easily solvable, but I guess a good compatibility with standard Django would be nice.

**Comment by wrabit** [comment]
@fbinz - thanks for words of support! I also see the benefits and enjoy the ease I can create my frontends now! I spotted your library recently and appreciated the clean approach in the loader.

I'll take a look at the issue

**Comment by wrabit** [comment]
Fixed in latest release [v0.9.39](https://github.com/wrabit/django-cotton/releases/tag/v0.9.39)
