### ISSUE TITLE
Django Cotton Performance problems

### ISSUE THREAD

**Issue by Dzirt07** [wrabit/django-cotton#131]
Good day, 

Using Django Cotton slowed down rendering by 6 times.

I really admire the concept of components (I know React, and it's very useful). That being said, I had a large template where I needed to render 34 cards with information. Django Cotton makes the code concise and easy to edit, but rendering the template without Django Cotton components takes 13 seconds, while rendering the same template with 34 Django Cotton components takes 65 seconds.

I’m not sure what I did wrong.
Here’s an example of a Django Cotton component:

`<c-card car="1" color="{{ car.color.TTD1 }}" runtime="{{ car.milege.TTD1 }}"></c-card>`

```
<div class="col-span-1 space-y-1">
  <div class="bg-gray-700 rounded-sm text-white text-center p-2 font-bold flex justify-center items-center">    
  <span class="text-lg">{{ car}}</span>
  </div>
  <div class="{{ color }} rounded-sm text-black text-lg text-center p-2 font-semibold">{{ milage}}%</div>
</div>
```

Do you have any idea why this is happening or how I might be able to improve the performance? Any guidance would be greatly appreciated!

[example-cotton.zip](https://github.com/user-attachments/files/16965406/example-cotton.zip)

**Comment by wrabit** [comment]
@Dzirt07 what type of objects are `{{ car.millege.HDD1 }}` etc? 

Also, are you on latest version of cotton?

**Comment by Dzirt07** [comment]
That's dictionary exported from pandas dataframe 

`{
    "milege": {
        "CAR9": 82,
        "CAR8": 73,
        "CAR6": 31,
        "CAR5": 67,
        "CAR4": 19,
        "CAR30": 58,
        "CAR3": 56,
        "CAR29": 38,
        "CAR28": 36,
        "CAR27": 17,
        "CAR26": 7,
        "CAR25": 0,
        "CAR24": 60,
        "CAR23": 82,
        "CAR22": 69,
        "CAR21": 40,
        "CAR20": 51,
        "CAR2": 70,
        "CAR19": 74,
        "CAR18": 74,
        "CAR17": 77,
        "CAR16": 68,
        "CAR15": 49,
        "CAR14": 59,
        "CAR13": 40,
        "CAR12": 23,
        "CAR11": 50,
        "CAR10": 63,
        "CAR1": 79
    },
    "color": {
        "CAR9": "bg-[#0A8000] text-white",
        "CAR8": "bg-[#FFF797] text-black",
        "CAR6": "bg-[#FFAD9C] text-black",
        "CAR5": "bg-[#FFAD9C] text-black",
        "CAR4": "bg-[#FFAD9C] text-black",
        "CAR30": "bg-[#FFAD9C] text-black",
        "CAR3": "bg-[#FFAD9C] text-black",
        "CAR29": "bg-[#FFAD9C] text-black",
        "CAR28": "bg-[#FFAD9C] text-black",
        "CAR27": "bg-[#FFAD9C] text-black",
        "CAR26": "bg-[#FFAD9C] text-black",
        "CAR25": "bg-[#FFAD9C] text-black",
        "CAR24": "bg-[#FFAD9C] text-black",
        "CAR23": "bg-[#0A8000] text-white",
        "CAR22": "bg-[#FFAD9C] text-black",
        "CAR21": "bg-[#FFAD9C] text-black",
        "CAR20": "bg-[#FFAD9C] text-black",
        "CAR2": "bg-[#FFAD9C] text-black",
        "CAR19": "bg-[#FFF797] text-black",
        "CAR18": "bg-[#FFF797] text-black",
        "CAR17": "bg-[#FFF797] text-black",
        "CAR16": "bg-[#FFAD9C] text-black",
        "CAR15": "bg-[#FFAD9C] text-black",
        "CAR14": "bg-[#FFAD9C] text-black",
        "CAR13": "bg-[#FFAD9C] text-black",
        "CAR12": "bg-[#FFAD9C] text-black",
        "CAR11": "bg-[#FFAD9C] text-black",
        "CAR10": "bg-[#FFAD9C] text-black",
        "CAR1": "bg-[#FFF797] text-black"
    }
}
`

**Comment by wrabit** [comment]
@Dzirt07 that doesn't align with the keys used in the example code..

**Comment by Dzirt07** [comment]
My bad 

Updated

**Comment by wrabit** [comment]
I would need a more thorough reproducible to look further.. things are running ok for me locally - 43.16 ms..

**Comment by Dzirt07** [comment]
Got it I will try, I also send you message in twitter/x

**Comment by mlissner** [comment]
I'm noticing in the release notes that the cache size introduced in 0.9.16 to fix this issue is 1024 items. Do I assume correctly that this is distinct components, not rendered ones? 

Thank you for the great package. We're evaluating it for CourtListener.com, and finding it to be really promising and interesting.

**Comment by wrabit** [comment]
@mlissner yes - this was more of a pre v1 patch until I got round to implementing better internal caching, shortly afterwards and along with a few other performance tweaks I switched to the same approach that django uses internally for caching `{% include %}` which uses the render_context and it became much more performant. The cause of the issue was also due to OP demanding a huge amount of data without any optimisation / pagination from the backend.
