### ISSUE TITLE
'submit' is not allowed. 

### ISSUE THREAD

**Issue by copyfactory** [wrabit/django-cotton#17]
Hello! 

There is an issue with passing the word 'submit' as a var.

```
<!-- button.cotton.html -->
<c-vars type="button"/>


<button type="{{ type }}">
  {{ slot }}
</button>
```

The following works and outputs `<button type="button">A button</button>` correctly.

```
<!-- view.cotton.html -->

<c-buttons.button>
    A button
</c-buttons.button>
```

However, the following outputs `<button>A button</button>`

```
<!-- view.cotton.html -->

<c-buttons.button type="submit">
    A button
</c-buttons.button>
```

Even stranger, if you change 'submit' to 'submitt' it works and outputs: `<button type="submitt">A button</button>`

```
<!-- view.cotton.html -->

<c-buttons.button type="submitt">
    A button
</c-buttons.button>
```

**Comment by wrabit** [comment]
Hi! I can't replicate it. My test:

```
<c-vars type="submit" />

<button type="{{ type }}">
  {{ slot }}
</button>
```

```
<c-buttons.issue-17-submit-value type="submit">
    Test
</c-buttons.issue-17-submit-value>
```

```
<button type="submit">Test</button>
```

Can you put `TEMPLATE_CACHING_ENABLED = False` in your settings.py to ensure caching isn't a part of it?

**Comment by copyfactory** [comment]
Thank you for the response!

Adding that setting unfortunately did not fix it.

I tried your example as well and it didn't work...

Will keep trying to see what is causing it. 

Another anomaly I noticed is that I have empty vars:
`<button ="">A submit button</button>`

So it's almost like it's being cleaned out at some point but I cant figure out why/when.

**Comment by wrabit** [comment]
Is there anything missing in your samples above? Any additional {{ or {% within the component definition?

Also which version of the package are you using?

Thanks

**Comment by copyfactory** [comment]
I used the example that you posted without any modifications.

Version: 0.9.6

Luckily it's not a huge deal since the default behavior of a button is to submit so doesn't alter any form logic and adding type=button to {{ attrs }} works fine for some reason.

Thanks again for your help

**Comment by wrabit** [comment]
No probs! it's good to find a bug so it can be resolved..

Could you let me know the version of django and python you are using? I would really like to be able to replicate.

**Comment by copyfactory** [comment]
Sure thing!

Django: 5.0
Python 3.10.0

I'm also using django-template partials but using the TEMPLATES config from the django-cotton still resulted in the issue for me, therefore I don't believe it is that.

**Comment by wrabit** [comment]
I'm noticing strange behaviour when I have installed template_partials, when you install the plugin using the default way (adding 'template_partials' to `INSTALLED_APPS`) it automatically modifies the `TEMPLATES` block. (https://github.com/carltongibson/django-template-partials/blob/main/src/template_partials/apps.py)

So I'm curious to know if you have that in your installed apps and if it works if it's removed . There is another way to install by using `template_partials.apps.SimpleAppConfig` which doesn't attempt to alter the settings.

**Comment by copyfactory** [comment]
Correct it wraps the Loader and injects its own so I use the SimpleAppConfig setup. This is what my templates currently look like:

```
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(APPS_DIR / "templates")],
        "APP_DIRS": False,
        "OPTIONS": {
            'loaders': [
                ('django_cotton.cotton_loader.Loader', [
                    'django.template.loaders.cached.Loader',
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader'
                ]),
                ('template_partials.loader.Loader', [
                    ('django.template.loaders.cached.Loader', [
                        'django_cotton.cotton_loader.Loader',
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ]),
                ]),
            ],
            'builtins': [
                'django_cotton.templatetags.cotton',
                'template_partials.templatetags.partials',
            ],
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.i18n",
                "django.template.context_processors.media",
                "django.template.context_processors.static",
                "django.template.context_processors.tz",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]
```

But for some reason even with template partials disabled, it wouldn't work? I'm very stumped as to why a word would not be permitted or cleaned out haha.

**Comment by wrabit** [comment]
Can you let me know what version beautifulsoup4 you are running in your environment? `pip show beautifulsoup4`

**Comment by copyfactory** [comment]
Sure thing.

Version: 4.12.3

**Comment by wrabit** [comment]
@copyfactory Unfortunately I have not been able to replicate with the info provided! It's a big ask but if you can provide reproducible code/repo it will be appreciated. For now I'll close it and will refer back to this issue should it recur.
