### ISSUE TITLE
Attributes requiring single quotes don't work

### ISSUE THREAD

**Issue by killianarts** [wrabit/django-cotton#176]
I use the HTMX inline partial pattern from Luke Plant (https://github.com/spookylukey/django-htmx-patterns/blob/master/inline_partials.rst#block-selection-in-the-template) regularly. The pattern relies on using `hx-vals='{"use_block": "some_block_in_my_template"}'`. Importantly, the first quotes need to be single quotes, not double quotes. However, Cotton seems to convert all single quotes to double quotes. It would be awesome if Cotton would keep the quotes as given.

**Comment by wrabit** [comment]
@killianarts which version are you running, there was [a PR](https://github.com/wrabit/django-cotton/blob/9e0b89c95373f68f319ca3ef1b27aa7ade430559/django_cotton/tests/test_attributes.py#L387) that added this functionality a while back..

**Comment by killianarts** [comment]
@wrabit I am on the latest version (1.1.1).

**Comment by mattbha** [comment]
In theory hx-vals of this nature would be supported.

perhaps we need to add some more tests and find if it broke

`hx-vals='{"use_block": "page-and-paging-controls"}'`

**Comment by mattbha** [comment]
@killianarts  i added a new test and 1.1.1 seems it supports it ok. can you confirm you are on the latest version and share the cotton template you are using? It's possible we are not testing some edge case.

cotton/htmx_vals.html

`<div {{ attrs }}></div>`

usage of component:
```
<c-htmx-vals
                hx-post="/root"
                hx-trigger="click"
                hx-vals='{"use_block": "page-and-paging-controls"}'
            />
```

renders
```
<div hx-post="/root" hx-trigger="click" hx-vals='{"use_block": "page-and-paging-controls"}'></div>
```

**Comment by killianarts** [comment]
<img width="706" alt="image" src="https://github.com/user-attachments/assets/7891bf33-443b-4d76-b08e-f608269b2a1e">

**form.html**
```html
<c-vars method="post" hx-swap="outerHTML" class />
<form action="." method="{{ method }}" hx-{{ method }}="." class="{{ class }}"
      hx-swap={{ hx_swap }} {{ attrs }}>
    {% csrf_token %}
    {{ slot }}
</form>
```

```html
<c-form hx-target="#dashboard-content"  hx-vals='{"use_block": "content"}'>
        {{ form }}
        <button name="submit" type="submit">
            {% trans 'Create Ticket' %}
        </button>
    </c-form>
```

**Comment by killianarts** [comment]
I originally wanted to do this:

```html
<c-vars method="post" hx-swap="outerHTML" block class hx-vals />
<form action="." method="{{ method }}" hx-{{ method }}="." class="{{ class }}"
      hx-swap={{ hx_swap }} hx-vals='{"use_block": "{{ block }}" {% if hx_vals %}, {{ hx_vals }}{% endif %}}' {{ attrs }}>
    {% csrf_token %}

    {{ slot }}
</form>
```

```html
<c-form hx-target="#dashboard-content" block="content" class="space-y-5" hx-vals='"test": "test_value"'>
```

But this is the rendered HTML:

```html
<form action="." method="post" hx-post="." class="space-y-5" hx-swap="outerHTML" hx-vals="{"use_block": "content" , "test": "test_value"}" hx-target="#dashboard-content">
```

**Comment by mattbha** [comment]
@killianarts I made this exact issue a test case using `1.1.1`

here is what was generated

```
<form
    action="."
    method="post"
    hx-post="."
    class="space-y-5"
    hx-swap=outerHTML
    hx-vals='{"use_block": "content" , &quot;test&quot;: &quot;test_value&quot;}'
    hx-target="#dashboard-content" >

</form>
```

**Comment by mattbha** [comment]
@killianarts not sure what to say about the issue you are facing. I will say regardless of the quotes composing hx-vals in the above fashion is a bit rough; I'd personally prefer to do something like (as hx-vals is inherited https://htmx.org/attributes/hx-vals/)

```
<c-vars method="post" hx-swap="outerHTML" block class hx-vals />
<div hx-vals='{"use_block": "{{ block }}"}'>
      <form 
            action="."   <!-- probably dont need this line due to using htmx over native forms -->
            method="{{ method }}"   <!-- probably dont need this line due to using htmx over native forms -->
            hx-{{ method }}="." 
            class="{{ class }}"   <!-- no default val so can probably rm this line and let it flow through attrs -->
            hx-swap="{{ hx_swap }}" 
            hx-vals='{{ hx_vals }}'   <!-- no default val so can probably rm this line and let it flow through attrs -->
            {{ attrs }}>
          {% csrf_token %}
          {{ slot }}
      </form>
</div>
```

**Comment by mattbha** [comment]
perhaps you can issue a `pip freeze | grep cotton` and confirm the version? I do see your screenshot, but the behavior you are witnessing is exactly as it was before the fix.

**Comment by killianarts** [comment]
Thanks! I ran pip freeze | grep cotton and it confirmed my version is 1.1.1. After some messing around with some other stuff, this problem seems to have resolved itself...

Thanks for the advice on constructing the component! `action` and `method` are there for progressive enhancement (plus my experience has been that less things mysteriously break if I do things the browser expects).

**Comment by wrabit** [comment]
@killianarts seems to be resolved but let us know if the issue comes back
