### ISSUE TITLE
Component not rendered when using Template.render()

### ISSUE THREAD

**Issue by danjac** [wrabit/django-cotton#182]
I have a working component something like this (in `COTTON_DIR/messages.html`):

```html
<div id="messages" {{ attrs }}>
 <!-- some content here.... -->
</div>
````

This is rendered correctly inside  another Django template:

```html
<div>
<c-messages /> 
</div>
```

which renders `<div id="messages...`.

However, in some Django middleware I have this:

```python
tmpl = '<c-messages />'
response.write(tmpl.render(RequestContext(request))
```

This renders **literally**  `<c-messages />`, in other words it looks like cotton is not parsing the template in this instance.

Is there a workaround for this?

**Comment by danjac** [comment]
I ended up using `render_to_string('cotton/messages.html')`

**Comment by wrabit** [comment]
@danjac yeah .render() bypasses the transformation that happens in loader, I don’t think we can hook into it at that point. You can technically use cotton’s django tags at that point ‘{% c messages %}..{% endc%} although not overly advised for now as this could change in future versions. Glad you found a way around it.

**Comment by danjac** [comment]
Right, where it doesn't work very well is when you have `{{ attrs }}` that you want to override, and there isn't an easy way I think to pass these attributes (other than as a plain string).

**Comment by wrabit** [comment]
@danjac in that case you would need to wrap in {% vars [attrs] %} .. all component content .. {% endvars %} similar to a with but this is where it starts to get tedious.

**Comment by danjac** [comment]
Another issue is having `<c-vars />` in the component template, which will break if the template is called directly e.g. in `render_to_string`. 

I ended up not using a component at all, going with a plain Django template.

It would be nice in some future version to have something like a `render_component` function to allow calling a component directly, which would be particularly useful in HTMX calls and the like - I think `django-components` has something like this.
