### ISSUE TITLE
cotton_loader.Loader append all apps templates directories to Engine.dirs (including Django ones)

### ISSUE THREAD

**Issue by alorence** [wrabit/django-cotton#188]
I had an issue with runserver_plus (from django-extensions) where many files were watched for changes while it is useless.
I found out that the issue diappeared when I removed `cotton_loader.Loader` from custom template loaders.

Django-extensions 'runserver_plus' relies on a Django builtin method to retrieve a list of templates directories :
```python
# django/template/autoreload.py
def get_template_directories():
    # Iterate through each template backend and find
    # any template_loader that has a 'get_dirs' method.
    # Collect the directories, filtering out Django templates.
    cwd = Path.cwd()
    items = set()
    for backend in engines.all():
        if not isinstance(backend, DjangoTemplates):
            continue

        items.update(cwd / to_path(dir) for dir in backend.engine.dirs if dir)

        for loader in backend.engine.template_loaders:
            if not hasattr(loader, "get_dirs"):
                continue
            items.update(
                cwd / to_path(directory)
                for directory in loader.get_dirs()
                if directory and not is_django_path(directory)
            )
    return items
```

There is 2 important things here:
1. All entries in `backend.engine.dirs` are returned by default, corresponding to paths in `settings.TEMPLATES[X]['DIRS']` (**global templates directories only**)
2. Each loader configured, having the `get_dirs()` method, is used to return all dirs it handle, **excluding directories from Django itself**

Unfortunately, in `cotton_loader.Loader`, we have:

```python
    @lru_cache(maxsize=None)
    def get_dirs(self):
        """This works like the file loader with APP_DIRS = True."""
        dirs = self.dirs if self.dirs is not None else self.engine.dirs

        for app_config in apps.get_app_configs():
            template_dir = os.path.join(app_config.path, "templates")
            if os.path.isdir(template_dir):
                dirs.append(template_dir)

        return dirs
```

In particular, the line `dirs = self.dirs if self.dirs is not None else self.engine.dirs` is problematic because `dirs` **references** the `Engine.dirs` member. The next loop will iterate over all apps 'templates' directory and append its path to dirs, **appending this path to `Engine.dirs` too**.

Once it has been executed, `get_template_directories()` from autoreload.py will return django templates directories, unfiltered, because they now come from Engine.dirs and not anymore from `app_directories.Loader.get_dirs()`

I think there is multiple ways to fix that, depending on the real need of the loader (I am not an expert in that field)

1. Is it really necessary to return all 'templates' directories from other loaders? As I understand, cotton loader should returns only `settings.COTTON_DIR` with a default to directoy 'cotton', no?
2. Maybe looping in app_dirs() could be avoided, at least when `django.template.loaders.app_directories.Loader` is NOT listed in `settings.TEMPLATES[X]['OPTIONS']['loaders']`, which correspond to a default config with APP_DIRS = False
3. Finally, a deep copy of the engine.dirs content, will prevent this behavior:

```python
dirs = list(self.dirs or self.engine.dirs)
```

a simple example:
```python
>>> mylist = ["a", "b", "c"]
>>> id(mylist)
140541412755904
>>> dirs = mylist
>>> id(dirs)
140541412755904  # same
>>> dirs
['a', 'b', 'c']
>>> dirs.append("x")
>>> dirs
['a', 'b', 'c', 'x']
>>> mylist
['a', 'b', 'c', 'x']
>>> dirs2 = list(mylist)
>>> id(dirs2)
140541408131456
>>> dirs2
['a', 'b', 'c', 'x']
>>> dirs2.append("zzz")
>>> dirs2
['a', 'b', 'c', 'x', 'zzz']
>>> mylist
['a', 'b', 'c', 'x']
```

**Comment by alorence** [comment]
By the way, I forget to thank you a lot for this incredible library. I am migrating a project from other django component library to this one, and it is a real pleasure to see such a clean and straitforward syntax !
I think this tool is a game changer for the future of Django, with some other like HTMX, django-template-partials, etc. !

**Comment by alorence** [comment]
Digging more into the issue, I understand now why the loader must returns all templates directory, because it mainly parses templates looking for used components (\<c-foo \>,  \<c-bar\>, etc.)

Performing a copy of self.engine.dirs instead of referencing it by a variable fixes the issue. PR #191 is open

**Comment by wrabit** [comment]
@alorence this is an area that does need some review as it may be a little 'hungry' right now, but yes your conclusion is right, we need to also process the non-cotton templates to see where cotton components are being included. Thanks for the support and catching this side effect, will review the PR shortly.
