### ISSUE TITLE
Passing down hyperscript to attrs with selector / HTML attribute are auto-completed

### ISSUE THREAD

**Issue by alfonsrv** [wrabit/django-cotton#198]
This might be very niche, but I'm using [_hyperscript](https://github.com/bigskysoftware/_hyperscript) (which is an  library of the maker of [htmx](https://github.com/bigskysoftware/htmx))

When passing down a hyperscript directive as part of `{{ attrs }}`, things that look like HTML tags are autocompleted. So this:

```html
<c-foo _="on click from <span[role='button']/> log event"> </c-foo>
```

becomes:

```html
<div _="on click from <span[role='button']></span[role='button']> log event">
```

which breaks the syntax. Maybe attrs having encapsulated parentheses values can be ignored for autocompletion?

**Comment by wrabit** [comment]
Hi @alfonsrv can you confirm you are using the latest version? Earlier uses BS4 which will attempt to “fix” html.

**Comment by wrabit** [comment]
@alfonsrv closing for now, please let me know if you still have issues with this
