### ISSUE TITLE
Component whitespace results in unwanted whitespace in the place of inclusion

### ISSUE THREAD

**Issue by KucharczykL** [wrabit/django-cotton#199]
Example:

```
This is an example (<c-test>This is in parentheses</c-test>)
```

templates/cotton/test.html
```
<span>
 {{ slot }}
</span>
```

Result:
```
This is an example ( This is in parentheses )
```

The only way to fix it seems to be removing whitespace from the component definition:

```
<span>{{ slot }}</span>
```

**Comment by wrabit** [comment]
@KucharczykL can you confirm the version of cotton? Thanks

**Comment by KucharczykL** [comment]
Hi @wrabit, apologies for not including it in the original report. I was using 0.9.37 before, now I have updated to 0.9.40 and the issue persists.

**Comment by wrabit** [comment]
I suspect upgrading to the latest (1.2.0) will resolve this. The compilation process was overhauled >=1.0.0.

**Comment by wrabit** [comment]
@KucharczykL closing for now, please let me know if you still have issues with this.

**Comment by KucharczykL** [comment]
@wrabit I have updated to 1.2.0 and the issue still persists.

**Comment by wrabit** [comment]
@KucharczykL Thanks for reporting, I'll take a closer look.

**Comment by wrabit** [comment]
Django's `{% include %}` tags have the same effect. Vue, Svelte by default 'condenses' whitespace, I think React/jsx takes a different approach and preserves it.

I think we can enable whitespace condensing by default and there should probably be a new config item to retain the existing behaviour.

**Comment by wrabit** [comment]
Having looked into this further the way it is now is how any typical html works:

```html
(<span>
Anything
</span>)
```

Will result in `( Anything )`

Some specific consideration will have to be made if we were to offer whitespace control here. As in, will we need to check if we're inside a `<pre>` tag before we perform this. I think it's reasonable to manage your html in these cases for now. But should there be some consensus for a solution, I will for sure take another look.

**Comment by KucharczykL** [comment]
It's true that's how typical HTML works and I understand that it might be confusing to change the default.

For me the result was surprising because I consider the component to be an encapsulated unit and I do not expect its internal structure to leak. Consider these examples:

```
Text (<c-test>More text</c-test>)
```


```
Text (
<c-test>More text</c-test>
)
```
or even

```
Text (
<c-test>
 More text
</c-test>
)
```

I understand the behind-the-scenes of why it adds whitespace but it doesn't feel "right" that it works that way. Well, to me anyway :slightly_smiling_face: Maybe other people can chime in.
