### ISSUE TITLE
Big difference in whitespace between 1.0.12 and 1.2.1

### ISSUE THREAD

**Issue by ra-dave** [wrabit/django-cotton#206]
@wrabit I have a rather large web page with many components on it.  I saved the rendered page that was using cotton 1.0.12 and then 1.2.1 and the files are 154kb and 177kb in size, respectively.   1919 lines vs 2189 lines. 

Here's an example.  On the left is 1.2.1 and on the right is 1.0.12.  This is pretty typical throughout the files:

![image](https://github.com/user-attachments/assets/40ad3413-291e-4985-8c85-62307167e1f4)

The left is what my original code looks like so I guess 1.0.12 was actually removing excess whitespace?  That was a nice "feature" :)

**Comment by wrabit** [comment]
@ra-dave yes so the compilation was completely changed between these 2 versions. Cotton used to use BS4 to parse and process html, which in turn automatically formats and cleans the html. It wasn't ideal that it tried to validate and change things in the html, so I moved to a regex based compilation method, which more or less now leaves html as-is. If you need to trim whitespace / minify html then I think you could look at some package or build your own simple middleware that achieves this. There is some idea that we can manage this in cotton in future but no concrete plan yet.
