### ISSUE TITLE
Default named slot?

### ISSUE THREAD

**Issue by randallmlough** [wrabit/django-cotton#207]
Is it possible to have a default named slot element if one is not provided?

Sudo example of what I'm trying to do (this obviously doesnt work)

_cotton component_
```html
# drawer.html
<c-vars button>
    <button type="button">
        Open
    </button>
</c-vars>

<div x-data="{ open: false }" >
    <span x-on:click="open = true">
        {{ button }}
    </span>
    <div>{{slot}}</div>
</div>
```

_overriding default button_
```html
<c-drawer>
      <c-slot name="button">
            <button>
               This overrides the default named slot
            </button>
        </c-slot>

        <div>panel content</div>
</c-drawer>
```

_using default button_
```html
<c-drawer>
      <div>panel content</div>
</c-drawer>
```

**Comment by wrabit** [comment]
@randallmlough for now no so you'll have to manage it like:

```html
{% if button %}
  {{ button }}
{% else %} 
  <button type="button">
    Open
  </button>  
{% endif %}
```

I've considered a cleaner option, this idea would be a breaking change:

```html
<!-- parent -->
<c-mycomp>
  <template slot="button">..</template>
</c-mycomp>
```

```html
<!-- component -->
<c-slot name="button"> I'm default </c-slot>
```

Essentially flipping the current usage of <c-slot ... > to be the placeholder in the component definition as opposed to the wrapping element defining the slot content. This is inspired by Vue and it seems more harmonious with native html + `<template></template>`

**Comment by randallmlough** [comment]
That's okay! I actually tried doing your example before posting, but I must have done something silly in my attempt because it wasnt working so I figured I couldnt access the name of the slot to be used in logic flows. but your example is perfectly fine with me and is doing what I want it to do. 

Thanks!
