### ISSUE TITLE
[Feature] Support for other file naming conventions

### ISSUE THREAD

**Issue by jlucasp25** [wrabit/django-cotton#208]
Hey, thanks for all the work on cotton.
This package is really the missing link between django and HTMX that me and others have been waiting for!

Is in the future plans to add support for other naming conventions to files?

I usually tend to have templates follow a structure with dashes instead of underscores, since it's not in the Python scope.
Something like nav-button.html instead of nav_button.html

Thanks!

**Comment by mattbha** [comment]
I prefer nav-button over nav_button as well, and I would prefer consistency between file names and usage within templates

**Comment by wrabit** [comment]
@jlucasp25 @mattbha 

I think it makes sense, I think the simplest way would be opt-in, eg. in settings: `COTTON_HYPHENATED_NAMES = True`

**Comment by wrabit** [comment]
@jlucasp25 @zkne @mattbha 

Released in [v1.3.0](https://github.com/wrabit/django-cotton/releases/tag/v1.3.0)

**Comment by mattbha** [comment]
seems to work great, project converted over successfully (and quickly)
