### ISSUE TITLE
Please let the `c-vars`  tag on regular `templates`

### ISSUE THREAD

**Issue by bal-sm** [wrabit/django-cotton#209]
I really like how I can put `title` of the page directly on `c-vars` of child template. I can do it on 0.9.32, but not on the latest.

Pretty please.

**Comment by wrabit** [comment]
Hey @bal-sm can you demonstrate the pattern a bit clearer so I can understand?

**Comment by bal-sm** [comment]
on `placeholder/templates/placeholder/some_view.html`:

```html
<c-vars title="Some View" />

<c-layouts.base-with-body title={{ title }}>
    <h1>{{ title }}</h1>
    <p>Wow, it's working.</p>
</c-layouts.base-with-body>
```

I really like how I don't need to put everything on `context` of the view. Just let dynamic things only on `context`. Would you agree?

**Comment by wrabit** [comment]
@bal-sm I can understand that it could be helpful in cases like this but I'd rather keep the reasoning of c-vars clear, for controlling component related state. I put forward an idea to implement a pattern that contains 'stack' and 'push' tags ([see here](#183)). This would allow us to control content from inside a component anywhere outside it. Vote it up to show support if you agree.
