### ISSUE TITLE
Is there a way to define default value for "Named slots"?

### ISSUE THREAD

**Issue by bal-sm** [wrabit/django-cotton#210]
It will be really helpful and cool, I think.

I mean if it can also have multi-lined `html` content as default value in _some different tag than `c-vars`_, perhaps?

**Comment by bal-sm** [comment]
and also can we work on how to properly define variation so we can just:

```html
<c-button:red>Delete account</c-button:red>
```

**Comment by copyfactory** [comment]
@bal-sm , @wrabit wrote a guide on creating variations for components. It's worth a read :).

https://medium.com/@willabbott/django-cotton-component-variants-for-smarter-reusability-07d8e4358ed0

**Comment by wrabit** [comment]
Hi @bal-sm, for now you will need to manage defaults this way:

```html
{% if named_slot %}
  {{ named_slot }}
{% else %}
  my default
{% endif %}
```

I would like to simplify the syntax and align it to Vue for example, ([see here](https://github.com/wrabit/django-cotton/issues/207#issuecomment-2419813899)) but nothing is planned in this moment..

About your suggested syntax of variation - there would be no way to say what you are configuring (a component could have many types of variation) so the keyed approach seems to be the most logical for now.
