### ISSUE TITLE
c-vars aren't always excluded from {{ attrs }}

### ISSUE THREAD

**Issue by fbinz** [wrabit/django-cotton#211]
There seems to be a bug (or a misunderstanding on my side) concerning `c-vars` and `{{ attrs }}`.

According to [the documentation](https://django-cotton.com/docs/components#excluded) `c-vars` should be excluded from `attrs`.

This is an example component, that highlights my problem:
```
<c-vars type="text" />
<c-vars class="" />

<div type="{{ type }}" {{ attrs }} class="abc {{ class }}">Hello World!</div>
```

When rendered using `<c-example class="xyz" />`, the result is `<div type="text" class="xyz" class="abc xyz">Hello World!</div>`, i.e. `class` is included in the `attrs`.
When you remove the `c-vars type` declaration, it works.

I've put together a small example project here: https://github.com/fbinz/django-cotton-test

You can run it using these commands:
```shell
uv venv
source .venv/bin/activate
uv sync
nanodjango run app.py
```

**Comment by wrabit** [comment]
Hi @fbinz you should use c-vars only once per component, this is probably what’s causing the unexpected behaviour.  So:

`<c-vars type="text" class="" />`

**Comment by wrabit** [comment]
Ill leave this open as a reminder to update the docs and readme.

**Comment by fbinz** [comment]
Ah, makes total sense! :D 
Now it works like a charm.

**Comment by wrabit** [comment]
Deployed new docs
