### ISSUE TITLE
Cotton components don't render in form templates

### ISSUE THREAD

**Issue by dotfrag** [wrabit/django-cotton#237]
Hello, I'm really enjoying cotton as it fits my mental model for front end components perfectly. Thank you for all the work!

I've hit a showstopper issue in my use case, where cotton won't render components in form templates. I checked through the docs but haven't seen anything mentioned.

Minimal example:

With component `core/templates/cotton/h1.html`:

```html
<h1 class="text-2xl font-bold">{{ slot }}</h1>
```

The code `<c-h1>Clients</c-h1>` in a random html template renders correctly:

```html
<h1 class="text-2xl font-bold">Clients</h1>
```

But in a form template:

`forms.py`:

```python
class ClientForm(ModelForm):
    template_name = "core/components/forms/default.html"
```

`core/components/forms/default.html`:

```html
...
<c-h1>Test</c-h1>
...
```

It doesn't:

```html
<c-h1>Test</c-h1>
```

I suspect this is related to where and how cotton hooks into Django's rendering lifecycle, and forms is not part of it.

Any help is appreciated.

**Comment by wrabit** [comment]
Hi @dotfrag, this isn't something that I've covered yet, maybe we will need to provide CottonModelForm which will add this functionality to the ModelForm class. There are no plans to support this for now, feel free to start a PR to support this.

**Comment by dotfrag** [comment]
Ah I see.. thanks. To be honest with you, I don't have the knowledge to help, and since I opened the issue I got fed up with Django's limited frontend support/tooling and I switched to a proper front-end network and kept Django as backend.

**Comment by wrabit** [comment]
@dotfrag ok fair enough

**Comment by LucienMarey** [comment]
Hello, just stumbled upon this issue while trying to resolve the problem fr myself.
It comes from the FORM_RENDERER setting defaulting to `django.forms.renderers.DjangoTemplates` in which there is no configuration for cotton loaders by default.
A workaround is to define a custom form renderer or to set `FORM_RENDERER` to `django.forms.renderers.TemplatesSetting` to use the same configuration as the `TEMPLATES` setting.
Maybe the library could provide a custom renderer out of the box ?

Here is my implementation:
```python
from functools import cached_property
from pathlib import Path

from django.forms.renderers import DjangoTemplates
from django.template.backends.django import DjangoTemplates as DjangoTemplatesBackend


class DjangoCottonFormRenderer(DjangoTemplates):
    @cached_property
    def engine(self) -> DjangoTemplatesBackend:
        return self.backend(
            {
                "APP_DIRS": False,
                "DIRS": [Path(__file__).parent / str(self.backend.app_dirname)],
                "NAME": "djangocottonforms",
                "OPTIONS": {
                    "builtins": [
                        "django_cotton.templatetags.cotton",
                    ],
                    "loaders": [
                        (
                            "django.template.loaders.cached.Loader",
                            [
                                "django_cotton.cotton_loader.Loader",
                                "django.template.loaders.filesystem.Loader",
                                "django.template.loaders.app_directories.Loader",
                            ],
                        )
                    ], },
            }
        )
```
