### ISSUE TITLE
Passing attrs through components?

### ISSUE THREAD

**Issue by curvedinf** [wrabit/django-cotton#239]
Hello, I am trying to pass the attrs of a component down into a next-level component for inheritance reasons. When I do, it produces some gobbledygook in the rendered html.

For instance

```
{# a.html #}
<svg {{attrs}}>{{slot}}</svg>
```
```
{# b.html #}
<c-a {{attrs}}>{{slot}}</c-a>
```
```
{# template.html #}
<c-b
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
>
    <path ...>
</c-b>
```

I also tried to pass it using a dynamic attribute like `<c-a :attrs="attrs"></c-a>` but that doesn't work either.

Is there a way to make this work?

**Comment by wrabit** [comment]
Hi @curvedinf, it's not ready yet but there's an open issue for it here https://github.com/wrabit/django-cotton/issues/192, closing this in favour of that one.

**Comment by wrabit** [comment]
Proxying and passing {{ attrs }} dict now supported in [2.1.0](https://github.com/wrabit/django-cotton/releases/tag/2.1.0)
