### ISSUE TITLE
Performance consideration when using cotton

### ISSUE THREAD

**Issue by amitjindal** [wrabit/django-cotton#44]
Hi @wrabit 

First and foremost, I absolutely love the idea behind this project. This is just fascinating and I have been looking for something like this for a very long time.

I was trying this and my first concern was what kind of performance hit this would cause for a project.

We wrote a small test case and while it was not running in production, we did see an order of magnitude difference in {% include "..." %} vs using the component.

Do you or anyone has done any performance testing? Or are there any tricks we can use to improve the performance.

Regards
Amit

**Comment by wrabit** [comment]
@amitjindal thanks for the support for the idea.

It's on my list to make some sections in readme + docs about performance and caching.

Make sure you have set a cache in Django, if you haven't already?

There is a render test, `render_load_test.py` which renders the test 10k times, I have just expanded it to cover a simple `{% include %}` test and the results I have are (running it a few times yields varying results, sometimes native coming out first) so there should be little in it:

```
Include, native vs cotton:
Native {% include %}: 0.34908294677734375 seconds
Cotton for include:: 0.31215786933898926 seconds
-------
Block + Extends, native vs cotton:
Native {% block %} and {% extends %}: 1.4457731246948242 seconds
Compiled Cotton Template: 1.448674201965332 seconds
```

The tests are not advanced so there may be some case that I am not considering here.

**Comment by amitjindal** [comment]
@wrabit I tried the test you mentioned and it indeed gives this output. I tried a little different version of that and here's the output.
I realise that this is probably not a realistic scenario but anyway documenting this here if its ever of concern.

Changes in your test case:

## 1. In example_project added these files: 

`templates/simple_cotton.html`

```html
{% for d in data %}<c-test>{{ d }}</c-test>{% endfor %}
```

`templates/simple_native.html`
```html
{% for d in data %}<h2>{{ d }}</h2>{% endfor %}
```

`templates/cotton/test.html`
```html
<h2>{{ slot }}</h2>
```

## 2. In `render_load_test.py` added:

```python
def benchmark_template_rendering_alt(template_name, iterations=10000):
    data = list(range(1, iterations))
    start_time = time.time()
    render_to_string(template_name, context={'data': data})
    end_time = time.time()
    return end_time - start_time, render_to_string(template_name)

simple_native = benchmark_template_rendering_alt("simple_native.html")
simple_cotton = benchmark_template_rendering_alt("simple_cotton.html")

print(f"Native Django Template: {simple_native} seconds")
print(f"Cotton Template: {simple_cotton} seconds")
```

## 3. Ran: `python render_load_test.py`, output was:

```
Native Django Template: (0.07367181777954102, '') seconds
Cotton Template: (0.5469141006469727, '') seconds
```

We probably won't have as many renders but this is what we were originally testing and got slow runs.
Any change we can do to improve this?

Again thanks for this wonderful initiative.
-Amit

**Comment by wrabit** [comment]
@amitjindal Thanks for the report! I had a similar discovery yesterday and currently working through a refactor to reduce the number of roundtrips we have to make to the cache. I'll report back here to let you know when something is ready.

**Comment by wrabit** [comment]
@amitjindal  Feel free to checkout the PR'd branch `caching_in_cotton_component`. On my machine at least, it's about halved the time. Reducing the number of iterations does bring it substantially down and lower than the native django version in your render tests.

**Comment by amitjindal** [comment]
@wrabit Bravo!!
This is amazing outcome. I am getting seriously good results.

Native Django Template: 0.08887982368469238 seconds
Cotton Template: 0.12306785583496094 seconds

Whenever you can release this.
I am marking this issue closed.

👏 👏 👏 

Thanks
Amit

**Comment by wrabit** [comment]
@amitjindal Thanks for confirmation 👍 it's not quite ready for release yet as I need to implement a way to dynamically manage the cache during development. We could simply turn it off when DEBUG = True but it would be preferable to give devs a realistic experience of performance even during building. 

I'll ping you when I have something.

**Comment by wrabit** [comment]
@amitjindal As mentioned 
- https://github.com/wrabit/django-cotton/releases/tag/v0.9.16

**Comment by amitjindal** [comment]
Already done? Amazing. 
Thank you so so much for this. Really appreciate it. 😄
