### ISSUE TITLE
Encode special characters

### ISSUE THREAD

**Issue by zagro-dev** [wrabit/django-cotton#60]
## Issue
In German we have special characters like Ä, Ö, Ü and ß. But I've tested also cyrillic, arabic and greek.

Enablind the `django_cotton.cotton_loader.Loader` in the `TEMPLATE['OPTIONS']['loaders']` settings.py will lead to display all these characters loaded directly from an  html page incorrectly.
e.g. `Händler` is displayed as  `HÃ¤ndler`

This is only true for directly in HTML "hardcoded" words.

## Example

```html
<html lang="de">
<head>
    <meta charset="utf-8">
    ...
</head>
<body>
    <h1>Test Ä Ö Ü ß</h1>  <!-- This will be messed up as described above -->
    <p>Добрый день.</p>
    <p>الخير.</p>
    <p>καλό απόγευμα</p>
    <ul>
    {% for user in users %}
    <li>{{ user.get_name }}</li>  <!-- This is displayed correctly even if the name has special characters  -->
    {% endfor %}
    </ul>
</body>
</html>
```

### Result
Test Ã„ Ã– Ãœ ÃŸ
Ð”Ð¾Ð±Ñ€Ñ‹Ð¹ Ð´ÐµÐ½ÑŒ.
Ø§Ù„Ø®ÙŠØ±.
ÎºÎ±Î»ÏŒ Î±Ï€ÏŒÎ³ÎµÏ…Î¼Î±
* Jürgen Gärtner
* Thomas Große

## What I've tried
I tried changing the encoding inside the `<head>` and inside Djangos `TEMPLATES['OPTIONS']['file_charset']` without success.
Here's my full TEMPLATES settings in case I'm missing something:

````python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'django_cotton.cotton_loader.Loader',  # uncommenting this line will resolve the issue but obviously will break c-cotton
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
            'builtins': [
                'django_cotton.templatetags.cotton',
            ],
            'file_charset': 'utf-8',  # default: utf-8
        },
    },
]
```

**Comment by wrabit** [comment]
@zagro-dev Having troubles replicating, can you verify the encoding of the template files? Run `file --mime-encoding *` in the template directory to determine.

**Comment by zagro-dev** [comment]
@wrabit I have configured several new Django projects with all default settings to reproduce the problem.
After some testing, I have come closer to solving the problem.
My dev environment runs on Windows 11. Only there the problem occurs regardless of the Django (4.2-5.0 tested) and/or Python version (3.10-3.12 tested).
The error does NOT occur on a Linux machine.

The files are (strangely enough) encoded both on Windows and on Linux partly as `utf-8` and partly as `us-ascii`, which makes no difference. It works on Linux and not on Windows.

This is a great insight for me, because it means I can continue to use this great project in my project, as my production server runs on Linux ;)
And maybe you can use this information to fix the problem on Windows.

**Comment by wrabit** [comment]
I noticed we were not setting the encoding properly on template file opening, this has been changed in the latest release. Please check it out and let me know if it resolves and thanks for the thorough feedback.

https://github.com/wrabit/django-cotton/releases/tag/v0.9.20

**Comment by zagro-dev** [comment]
Solved. Thanks for this quick fix!
