### ISSUE TITLE
Support for Rendering Components App-Based Template Folders

### ISSUE THREAD

**Issue by zkne** [wrabit/django-cotton#63]
First of all, great job on this library!

I have encountered an issue with rendering components in templates when using app-based templates. In more complex projects, it is common to use both top-level template folder and app-based template folders. It would be fantastic if support for this use case could be added.

**Comment by wrabit** [comment]
Hi @zkne thanks for the feedback! Just to explore your issue a bit more. Is there a reason why you don't consider to add your app directories manually to the `TEMPLATES['DIRS']` list? Or were you hoping for something more automated?

**Comment by zkne** [comment]
Hi @wrabit, I'm looking for a more automated solution as I have a lot of apps. I'm relying on the `Django.template.loaders.app_directories.Loader` to pick up each directory. 

The main `templates` directory has all of the shared templates, like base, sidebar, header, cotton, and more, and each app templates directory has templates for individual pages provided by the app.  

You are correct that manually defining each route to the app templates directory in `TEMPLATES['DIRS']` will do the job, but I would like to avoid that.

**Comment by wrabit** [comment]
@zkne done in https://github.com/wrabit/django-cotton/pull/67 and released in 0.9.22

**Comment by zkne** [comment]
Awesome 👏
