### ISSUE TITLE
{{ attrs }}  '=' equal issue

### ISSUE THREAD

**Issue by aaltatan** [wrabit/django-cotton#64]
First of all, great job on this library!

I have encountered an issue with using '=' sign inside the value of one of the html attributes in the component like this:

```
<c-context-item
  hx-get="{% url 'faculties:delete' pk=faculty.pk %}"
  hx-target="#modal"
  hx-swap="innerHTML"
  @click="modalOpen = true"
>{% translate 'delete' %}</c-context-item>
```

too many values to unpack (expected 2)

i found a silly solution like:

```
{% with '=' as eq %}
<c-context-item
  hx-get="{% url 'faculties:delete' pk=faculty.pk %}"
  hx-target="#modal"
  hx-swap="innerHTML"
  @click="modalOpen {{ eq }} true"
>{% translate 'delete' %}</c-context-item>
{% endwith %}
```

i hope you will fix this.

a lot of thanks

**Comment by wrabit** [comment]
Thanks for reporting the issue! Fixed in 0.9.21

- https://github.com/wrabit/django-cotton/releases/tag/v0.9.21
