### ISSUE TITLE
Suggestion: props as boolean attributes

### ISSUE THREAD

**Issue by shakedown-street** [wrabit/django-cotton#7]
I'm not sure how hard this would be to implement, but it'd be nice to be able to pass props as boolean attributes rather than key/value pairs.  As an example, a `rounded` prop on a button component.

Being able to do something like:

`<c-button rounded>Click me</c-button>`

Rather than:

`<c-button rounded="true">Click me</c-button>`

**Comment by wrabit** [comment]
@shakedown-street Yes, it's something I have wanted also. I think it makes sense that it would deliver a real python boolean True to the component so you can do:

{% if rounded %} ... {% endif %} 

If it's just a string value 'true' / 'false' it would require us to do rounded == 'true' also cater for any case difference.

**Comment by wrabit** [comment]
Added in #8 

https://django-cotton.com/docs/components#boolean-attributes

**Comment by shakedown-street** [comment]
Awesome!
