### ISSUE TITLE
Not really an issue, great package

### ISSUE THREAD

**Issue by Tobi-De** [wrabit/django-cotton#70]
I was wondering if it was possible to define a component like this
```html
<!-- cotton/button.html -->
<a href="{{ url }}" class="...">
    {{ slot }}
  
    {% if icon %} 
        {{ icon }} 
    {% endif %}
</a>
```

and do this

```html
<!-- in view -->
<c-button url="/contact">
    Contact
    <c-icon>
        <svg>...</svg>
    </c-icon>
</c-button>
````

insead of this 
```html
<!-- in view -->
<c-button url="/contact">
    Contact
    <c-slot name="icon">
        <svg>...</svg>
    </c-slot>
</c-button>
````

How difficult would it be to implement?

**Comment by wrabit** [comment]
It's not going to play that well because it's mirroring the api for an actual component. Not only compilation will be more complex but imagine arriving at the view code, you wouldn't know if you were looking at a nested component or a slot. Was thinking of something related recently due to a different feature Im working on and what may be preferable in that scenario was `<c-slot:icon>`. Would be interested to know your drive for this idea.

**Comment by Tobi-De** [comment]
> Not only will compilation be more complex, but imagine arriving at the view code; you wouldn't know if you were looking at a nested component or a slot.

I didn't think of that. You are right; it would be quite confusing.

I'm building a Tailwind components library based on Cotton. I was just trying to avoid creating separate files like `c-accordion-title` and `c-accordion-content` myself and defining everything in a single component file. Slots are actually a good candidate for what I'm trying to do, and I know it's a feature available in frontend frameworks, but I almost never see them being used in component libraries.

```html
<c-accordion>
  <c-accordion-title>Accordion Title</c-accordion-title>
  <c-accordion-content>
    Some accordion content
  </c-accordion-content>
</c-accordion>
```

```html
<c-accordion>
  <c-slot name="title">Accordion Title</c-slot>
  <c-slot name="content">
    Some accordion content
  </c-slot>
</c-accordion>
```

Maybe because option 1 looks better than option 2? What do you think? A syntax like `c-slot:icon` would definitely make the second option look better. Which one would you prefer to write?

**Comment by wrabit** [comment]
I can understand your situation and I would too be trying to optimise the usage but slots are very different to passing actual nested components, that is you cant position nested components in the parent. I know you provided just an example but to simplify I would not be passing an explicit "content" named slot but just allow it to be the default {{ slot }} 


```
<c-accordion>
  <c-slot name="title">Accordion Title</c-slot>
  Some accordion content
</c-accordion>
```

**Comment by Tobi-De** [comment]
> I can understand your situation and I would too be trying to optimise the usage but slots are very different to passing actual nested components, that is you cant position nested components in the parent. I know you provided just an example but to simplify I would not be passing an explicit "content" named slot but just allow it to be the default {{ slot }}
> 
> ```
> <c-accordion>
>   <c-slot name="title">Accordion Title</c-slot>
>   Some accordion content
> </c-accordion>
> ```

This is how I actually started it, and I began to wonder: what if the user wants to customize the classes in the content or the title separately, or even change their positions? But I'm definitely overthinking this. It's not that common to try to override classes on existing components; usually, you just create your own

**Comment by wrabit** [comment]
Theres an undocumented feature.

```
<el {{ attrs_dict|merge:"class: pt-8" }}>
```

attrs_dict gets passed to all components. Merge filter lets you specify additional items for attributes so in this sample it will add pt-8 to the {{ attrs }} string. It's not documented yet because I wasn't happy with the feature yet.

**Comment by wrabit** [comment]
Another idea would be to allow slots to have attributes so you can have more control over configuration:

```html
<!-- usage -->
<c-accordion class="something">
  <c-slot name="title" class="something-else">
  </c-slot>
</c-accordion>
```

```html
<!-- accordion.html -->
<div class="{{ class }}">
  <div class="{{ title.class }}">
    {{ title }}
  </div>
</div>
```

**Comment by Tobi-De** [comment]
> Another idea would be to allow slots to have attributes so you can have more control over configuration:

Oh yeah, definitely. I thought that was already the case—that slots work like regular components where you can pass attributes, objects, etc., although I haven't tried it yet.
