### ISSUE TITLE
Django-cotton info on snyk

### ISSUE THREAD

**Issue by millsks** [wrabit/django-cotton#71]
Information on snyk is not accurate. Is it possible for you to look into this? We are seeing the following error at the top and missing metrics throughout. 

"Unable to verify the project's public source code repository."

https://snyk.io/advisor/python/django-cotton

**Comment by millsks** [comment]
Thank you!

**Comment by wrabit** [comment]
Actually it looked fine to me without doing anything, they were probably just updating.
