### ISSUE TITLE
Dynamic components

### ISSUE THREAD

**Issue by wrabit** [wrabit/django-cotton#72]
In an addon I'm developing for Cotton, I have a need to be able to set the component name via a template variable. Following suit with Vue/Blade I think about a special tag like

`<c-component :is="variable" />`

Which will compile to 

`{% cotton_component :is=variable %}`

An example of use-case, I have a list of icons which are created as cotton components that I want to display:

```html
{% for icon in icons %}
  <c-component :is="icon" />
{% endfor %}
```

Something else to consider is whether we aim to allow template expression here, like:

`<c-component :is="some.initial.path.{{ variable }}" />`

Which _may_ be possible using the current expression type attribute mechanism.

Note: It could be a breaking change to those with existing components named as 'component'. And we should raise an exception if <c-component> tag is used without an `is` / `:is` attribute.

**Comment by zkne** [comment]
This would be a great add-on to the library. 
How do you plan to distinguish components with the same name but in different subfolders?

**Comment by wrabit** [comment]
@zkne so subfolders are already supported, a la:

`<c-subfolder.my-component />`

So the variable would have to contain the path, i.e. using `add:` filter as in: `comp="subfolder."|add:comp"`.

But better for DX would be to allow also the approach I mentioned:

`<c-component is="subfolder.{{ comp }}" />`

It will be slightly less performant, I just need to assess how much less..

**Comment by zkne** [comment]
`<c-component is="subfolder.{{ comp }}" />` would be a preferred way in my opinion, even if it's less performant.

**Comment by wrabit** [comment]
Released in https://github.com/wrabit/django-cotton/releases/tag/v0.9.32
