### ISSUE TITLE
Improve setup, integrate APP_DIRS = True

### ISSUE THREAD

**Issue by wrabit** [wrabit/django-cotton#81]
It's been noted more than once that the setup is not ideal, particularly because the current installation requires you to set APP_DIRS = False (thus forcing you to provide all app template dirs manually), this is due to a Django requirement that you cannot specify a custom loader AND have APP_DIRS = True at the same time.

One idea is that we replicate the filesystem + app directory loaders within the Cotton loader, so although you have to do APP_DIR = False, everything will work like normal.

A pitfall is the loss of clarity when viewing the settings.py, it's not obvious that cotton will be picking this functionality up. Additionally, for some reason this behaviour may not be desirable, so to address both of these, we could pass the cotton loader an explicit setting, i.e.:

```python
TEMPLATES = [
    {
        ...
        'DIRS': [],  # Can remain empty
        'APP_DIRS': False,  # This must be False when using custom loaders
        'OPTIONS': {
            'loaders': [
                ('django_cotton.cotton_loader.Loader', {
                    'app_dirs': True
                }),
            ],
        },
    },
]
```

Maybe there is something simpler that I am missing.. comments welcome!

**Comment by ra-dave** [comment]
In my case, settings APP_DIRS to False breaks my django-tailwind installation:

django.template.exceptions.TemplateDoesNotExist: tailwind/tags/css.html

Not sure what the fix is.  I assume I need to set additional folders in the DIRS setting but I haven't figured it out yet.  This is the only css.html file in my entire project folder:

venv\Lib\site-packages\tailwind\templates\tailwind\tag\css.html

**Comment by wrabit** [comment]
@ra-dave cotton requires a loader, Django out of the box complains if APP_DIRS = True whilst a custom loader is defined. To be up and running for now, the answer is to explicitly list the template paths in your project. But if you check back here in sometime, there's a good chance a more automated approach will be introduced.

**Comment by ra-dave** [comment]
I think my issue with setting APP_DIRS to False is more of a problem with my tailwind package installation.  It shouldn't be referencing the needed files out of venv/Lib/site-packages but should instead be copying them to my project.  

Setting DIRS to this solved my problem but obviously I need to figure out a better way:

'DIRS': [ BASE_DIR / 'templates', BASE_DIR / 'venv/Lib/site-packages/tailwind/templates', BASE_DIR / 'venv/Lib/site-packages/meta/templates' ],

**Comment by ra-dave** [comment]
I have created a minimal test project that demonstrates the problem I am having with template not found error.   If you comment out the loaders section in OPTIONS it works.  If you uncomment it it doesn't work.

[test1.zip](https://github.com/user-attachments/files/16666630/test1.zip)

**Comment by mariusgronli** [comment]
> It's been noted more than once that the setup is not ideal, particularly because the current installation requires you to set APP_DIRS = False (thus forcing you to provide all app template dirs manually), this is due to a Django requirement that you cannot specify a custom loader AND have APP_DIRS = True at the same time.
> 
> One idea is that we replicate the filesystem + app directory loaders within the Cotton loader, so although you have to do APP_DIR = False, everything will work like normal.
> 
> A pitfall is the loss of clarity when viewing the settings.py, it's not obvious that cotton will be picking this functionality up. Additionally, for some reason this behaviour may not be desirable, so to address both of these, we could pass the cotton loader an explicit setting, i.e.:
> 
> ```python
> TEMPLATES = [
>     {
>         ...
>         'DIRS': [],  # Can remain empty
>         'APP_DIRS': False,  # This must be False when using custom loaders
>         'OPTIONS': {
>             'loaders': [
>                 ('django_cotton.cotton_loader.Loader', {
>                     'app_dirs': True
>                 }),
>             ],
>         },
>     },
> ]
> ```
> 
> Maybe there is something simpler that I am missing.. comments welcome!

First of all congratulations on django-cotton! This is what I've been missing the most when im working with Django.

We keep our templates encapsulated within the app folder so we use APP_DIRS = True, and would need a solution for handling this before we can start using cotton. 

Your solution by passing a app_dirs var to the loader to replicate the filesystem + AppDirectoriesLoader seems good. I guess the ideal would be to use APP_DIRS inside TEMPLATES as the single truth, but i dont know if its possible to catch or bypass the ImproperlyConfigured: 'APP_DIRS' cannot be True when the 'loaders'.. 

As long as its explained in the docs why we have to pass app_dirs again to the loader i dont see any problem with it.

**Comment by gimntut** [comment]
It seems to me that it is necessary to abandon the indication of loaders.
Instead, make your own backend
```python
class CottonTemplates(DjangoTemplates):
    def __init__(self, params):
        super().__init__(params)
        self.engine.loader.insert(0, 'django_cotton.cotton_loader.Loader')

# setting
TEMPLATES = [
    {
        'BACKEND': 'CottonTemplates',
        'DIRS': ['your_project/templates'], # Add your template directories here
        'APP_DIRS': True,
        'OPTIONS': {
            'builtins': [
                'django_cotton.templatetags.cotton',
            ],
        },
    },
]
```

**Comment by wrabit** [comment]
@gimntut interesting - I will check this out

**Comment by wrabit** [comment]
Thanks for the suggestion but I went with doing it from `apps.py` in the end. Released in 
- https://github.com/wrabit/django-cotton/releases/tag/v0.9.29
