### ISSUE TITLE
Tab component example is confusing

### ISSUE THREAD

**Issue by ra-dave** [wrabit/django-cotton#82]
https://django-cotton.com/docs/alpine-js#modify-tabs

The final code in the example is missing the Tailwind styling, for example:

class="..."

I realize this was probably done so as to focus on the Alpine part, etc, but it's confusing if someone is expecting to copy/paste the code and have it just work.  A complete turn-key example would be better.

**Comment by wrabit** [comment]
You will find the classes if you follow from the first heading, "Start with a static prototype".
