### ISSUE TITLE
"date" filter returns empty string inside component

### ISSUE THREAD

**Issue by danjac** [wrabit/django-cotton#93]
Django 5.1,  django-cotton==0.9.31

Given this component: 

```html
<time  {% if title %}title="{{ title }}"{% endif %}
      datetime="{{ value|date:"c" }}">{{ value|date:"j M Y" }}</time>
```

and used like this: 

```html
    <c-timestamp value="{{ pub_date }}" title="My title" />
```

The rendered HTML is:
```html
<time title="My title" datetime=""></time>
```

i.e. `value` is stripped out from the HTML.  Without the `date` filter i.e. 

```html
<time  {% if title %}title="{{ title }}"{% endif %}
      datetime="{{ value }}">{{ value }}</time>
```

`value` is rendered in the HTML.

However, using `{% include %}` the template renders correctly.

For some reason, the bug only seems to affect `date` e.g. `capfirst` works.  I suspect the problem is that the component parameters are always rendered to string?

**Comment by danjac** [comment]
Tried passing by value with `:value=` but it seems that `date` or `datetime` values are not handled i.e.

```html
   <c-timestamp :value="{{ pub_date }}" title="My title" />
```

will still render an empty string.

**Comment by wrabit** [comment]
@danjac you are printing the variable with `{{ }}`. So the datetime is already evaluated by the time it get's to the filters and component. The correct way to pass the variable by reference is `:value="pub_date"` which should then work as expected.

**Comment by danjac** [comment]
Ah - makes sense. Works great, thanks!
