### ISSUE TITLE
Handling context in slots within loops

### ISSUE THREAD

**Issue by danjac** [wrabit/django-cotton#95]
I'm trying to build a "pagination" component like this:

```html
        <ul class="divide-y divide-solid" id="pagination">
            {% if has_other_pages %}
                <li class="pb-3">Previous</li>
            {% endif %}
            {% for item in page_obj %}<li class="py-3 first:pt-0 last:pb-0">{{ slot }}</li>{% endfor %}
            {% if has_other_pages %}
                <li class="pt-3">Next</li>
            {% endif %}
        </ul>
```

And it should work something like this:

```html
<c-paginator :page_obj="page_obj">
    <div>
    {{ item.title }}
   </div>
</-paginator>
```

However, `item` is empty, as it is not passed to the slot. According to the docs:

> The {{ slot }} variable will contain all of the content provided between the opening and closing tag of the current component as defined in the parent.

Which makes sense, but what would be the best way to handle passing per-loop context to a repeated slot?

**Comment by wrabit** [comment]
That pattern you're reaching for is generally known as scoped slots and it's not currently supported in cotton. For now I would either hardcode your pagination style inside the pagination component or if you need variation then use a conditional and a style attribute from the parent to choose which you want.

**Comment by danjac** [comment]
OK, good to know. As a workaround  I made a second component to handle the items:

```html
        <c-paginator :page_obj="page_obj">
        {% for item in page_obj %}
            <c-pagination-item>
            {{ item.title }}
            </c-pagination-item>
        {% endfor %}
        </c-paginator>

```

**Comment by wrabit** [comment]
@danjac yeah that's a good option
